### PR TITLE
Added - Support for bttv chat, and other stylers

### PR DESCRIPTION
**Pull request by goldbattle**
- Fixed missing emote class
- Now responsive inside the right panel
- Added some classes that allow for stylers to apply correct css
- Fixed random spelling error

### CODE REVIEW

**Comment by pencil** [comment]
Thank you! I love PRs that remove more code than they add while maintaining functionality.

Some minor things I noticed:

* The left border of the right column is missing:
   
   Before: image
   After: image
* Please use camelCase for variable names (`containerTab` instead of `container_tab` etc.)

**Comment by pencil** [comment]
I just noticed that the actual chat doesn't have that border so it say it's ok to not add it.

**Comment by goldbattle** [comment]
I am fine with leaving the border out, up to you.
- Converted things to camelCase
- Changed the chat padding

## Before
image

## After
image

**Comment by pencil** [comment]
Looks good! I'll do some more testing this week and then go ahead and merge it.

**Comment by pencil** [comment]
When you click on a username, this pops up:

image

I think some data-attributes are probably missing.

**Comment by goldbattle** [comment]
How are you getting that to popup, I can't seem to get it to show for the
life of me.

**Comment by goldbattle** [comment]
I added some data attributes, but I still can't get that popup to come up, not sure why that doesn't work on my system.

**Comment by pencil** [comment]
That seems to fix it:
image

The odd thing is, that this feature does only work, when you access a VOD via the profile page (`http://www.twitch.tv/<username>/profile). If you access the VOD URL directly (`http://www.twitch.tv/<username>/v/<id>), clicking on the username does nothing. Maybe you quickly want to look into this, but maybe it's a BTTV problem that we can't address.

**Comment by goldbattle** [comment]
I still can't get it to popup, but I found that I missed the styling on system messages.
Just committed a fix.

**Comment by pencil** [comment]
System messages are currently broken anyways. Twitch deprecated the `TWITCHCLIENT` command that I used to record these messages.

**Comment by goldbattle** [comment]
I check if the message is sent from the user `twitchnotify`.
But I have to send a raw `TWITCHCLIENT 3` to get it to give me all the
information I need.

**Comment by pencil** [comment]
`twitchnotify` messages should still work, that's true. Just the `jtv` messges are gone (Timeouts, Slow mode notifications etc.)

**Comment by goldbattle** [comment]
So here is what I have found.

For notifications on room status: [link](https://github.com/justintv/Twitch-API/blob/master/IRC.md#commands)
```
CAP REQ :twitch.tv/commands
1439090824451 @msg-id=slow_on :tmi.twitch.tv NOTICE #goldbattle :This room is now in slow mode. You may send messages every 10 seconds.
```

For getting user emote set, sub, turbo, etc status: [link](https://github.com/justintv/Twitch-API/blob/master/IRC.md#tags)
```
CAP REQ :twitch.tv/tags
1439090974296 @color=#008000;display-name=goldbattle;emotes=;subscriber=0;turbo=0;user-type= :goldbattle!goldbattle@goldbattle.tmi.twitch.tv PRIVMSG #goldbattle :message_here
```

For getting timeouts/ban: [link](https://github.com/justintv/Twitch-API/blob/master/IRC.md#clearchat)
```
1439091248147 :tmi.twitch.tv CLEARCHAT #goldbattle :other_user
```


It seems that the bans are not broadcasts, and the only thing is the clear message notice which supplies the user that should have their messages cleared, and is the closest thing to having the ban notice. The first line is the raw message you must send in order to subscribe to those notices.

**Comment by pencil** [comment]
Cool, thanks!

**Comment by goldbattle** [comment]
image image

Updated to match the `0.15.0` release. The only change is that the dynamic resizing code isn't needed any more since the chat now sites inside the correct right panel container.

**Pull request merged**
