### PR TITLE
Feature - VOD Theatre Mode

### PR DESCRIPTION
**Pull request by goldbattle**
Adds the theatre mode to the vod page.
I really liked having the theatre mode to remove the clutter from the page.

Works like normal theatre mode including:
- Added theatre mode button
- Added "Exit Theatre Mode" button
- Working esc key exit
- Working Alt+T toggle

I was not sure about the best place for placing listeners and the such, and this is just what I have working. Feel free to change anything you want, but the functions need to reside in the `injected.js` so the page scope can see them.

### CODE REVIEW

**Comment by pencil** [comment]
Wow, thank you! Probably one of the most requested feature. I will look into this and test it the coming weekend.

**Comment by pencil** [comment]
I will do some minor code changes and plan to release it by the end of the week.

**Comment by goldbattle** [comment]
Any update on this?
Thanks!

**Comment by pencil** [comment]
Sorry for the delay. Because of me starting a new job and the ReChat server issues I had basically no time to look into this. I am looking at it right now :smile:

**Comment by goldbattle** [comment]
Thank you!!

**Comment by pencil** [comment]
Good work, it seems to work almost flawlessly. They only problem I found is when first entering through the Theatre button you append and then pressing Alt+T, I end up with this:
image

**Comment by goldbattle** [comment]
Is this with the new html5 player or flash?

**Comment by pencil** [comment]
Seems to happen with both players. I just double checked it to make sure.

**Comment by goldbattle** [comment]
I don't seem to be able to reproduce this, I am using `chrome 44.0.2403.130 m`

**Comment by pencil** [comment]
I am on `Version 45.0.2454.26 beta (64-bit)`. Maybe it's a OS X specific problem.

**Comment by goldbattle** [comment]
Yep, seems that they key codes are different. I didn't know that, will switch it over to jquery's version.

**Comment by goldbattle** [comment]
Ok, can you give that a go?
It uses the jquery check for a meta key, which should support mac etc.
http://stackoverflow.com/a/5500536

**Comment by pencil** [comment]
`metaKey` is for the `Cmd` key. I think `altKey` would actually be the right one.

But I just checked in console:
image
Key codes look correct. They are the ones that you check for.

**Comment by goldbattle** [comment]
So just having the `if (e.altKey && key == 't')` would work for you?

**Comment by pencil** [comment]
No, probably not. The Alt key and the 't' key are two separate events if you are using `keydown`/`keyup`. I am not sure if it would work with `keypress`. Twitch might stop these events from propagating.

**Comment by pencil** [comment]
I was actually wrong. The code you suggested should work, good job! I am gonna do some refactoring and more testing.

**Comment by pencil** [comment]
I did some refactoring and fixed another bug (`keydown` handler was registered multiple times when browsing to another VOD). If you could test the `goldbattle-feature-vod-theatre` branch, that would be great.

**Comment by goldbattle** [comment]
Yep, it works, thanks again!

**Comment by pencil** [comment]
Thank you for your contribution! I currently don't have time to push an update but will do so on Monday evening.

**Comment by pencil** [comment]
FYI: I published the upgrade. Unfortunately some change must have triggered a ["manual review"](https://developer.chrome.com/webstore/faq#faq-listing-08) in the Chrome web store. Will publish the announcement once Chrome reviewed the changes.

**Pull request closed without merging**
